import { Open_Sans, Raleway } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Footer from './components/Footer';

const open_Sans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-open-sans',
});
const raleway = Raleway({
  subsets: ['latin'],
  weight: ['600', '800'],
  variable: '--font-raleway',
});

export const metadata = {
  title: 'Fruitables e-commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${open_Sans.variable} ${raleway.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
